#!/bin/bash

# Figure out script absolute path
pushd `dirname $0` > /dev/null
JQF_DIR=`pwd`
popd > /dev/null

# Check arguments
if [ $# -lt 3 ]; then
  echo "Usage: $0 TEST_CLASS TEST_METHOD MAX_TRIALS" >&2
  exit 1
fi

# Run the random input driver
$JQF_DIR/scripts/jqf-driver.sh edu.berkeley.cs.jqf.fuzz.drivers.RandomDriver $@
