#!/bin/bash

# Figure out script absolute path
pushd `dirname $0` > /dev/null
JQF_DIR=`pwd`
popd > /dev/null

# Check arguments
if [ $# -lt 3 ]; then
  echo "Usage: $0 TEST_CLASS TEST_METHOD INPUT_FILE" >&2
  exit 1
fi

# Ensure that proxy is built
if [ ! -f "$JQF_DIR/afl/proxy" ]; then
  echo "The AFL proxy is not built! Make sure to run scripts/setup.sh or run 'make' in afl/" >&2
  exit 2
fi


class=$1
method=$2
input=$3

a2j=/tmp/a2j
j2a=/tmp/j2a

rm -f $a2j
rm -f $j2a
mkfifo $a2j
mkfifo $j2a

# Run the AFL driver in the background
"$JQF_DIR/scripts/jqf-driver.sh" \
  edu.berkeley.cs.jqf.fuzz.drivers.AFLDriver $class $method $input $a2j $j2a \
  1> /dev/null 2> /dev/null &

# Run the proxy
"$JQF_DIR/afl/proxy" $a2j $j2a


