#!/bin/bash

# Counts BRANCH events in a trace file generated by `jqf-repro -i`
# Usage: count_branches.sh [TRACE_FILE (default is 'main.log')]

if [ -z "$1" ]; then
  trace_file="main.log"
else
  trace_file="$1"
fi

awk '
BEGIN {
  k = 0;
  FS = ","
}

/^ALLOC/ {
  counters[k] += $3;
}

/^# End/ {
  files[k] = substr($0, 6)
  k++;
}

END {
  for (k in counters)
    print counters[k], files[k];
}' "$trace_file"



